### ISSUE TITLE
Responsive design will be made for all parts

### ISSUE THREAD

**Issue by ErenYalcn** [ErenYalcn/getir-clone#1]
only compatibility issue with all screens remained and a few improvements

**Comment by mpnri** [comment]
`.grid-cols-10 {
    grid-template-columns: repeat(10, minmax(0, 1fr));
}` 
Hi,
by using "@media" for different device widths and changing "10" to less numbers and so for `.grid-cols-8`, I think it would be a more suitable design in smaller devices.

**Comment by ErenYalcn** [comment]
@mpnri thank you for help :)
